### ISSUE TITLE
Fix ipv4-only for unbound

### ISSUE THREAD

**Issue by feld** [chatmail/relay#738]
It's possible to deploy a Chatmail relay server that misbehaves because it tries to deliver to mail servers that have an AAAA and just fails. We should control sysctls and guard any setting for Postfix/Dovecot in the templates that enable IPv6 functionality 

edit: this is a rough placeholder issue as the reporter's GitHub account was banned and they need to make a new one. More information will be coming.

**Comment by link2xt** [comment]
It is currently opt-out, but there is a setting to disable it:
https://github.com/chatmail/relay/blob/8f68672e3112682055b8fdb6e0e8d6c473730f8c/chatmaild/src/chatmaild/ini/chatmail.ini.f#L63-L64

**Comment by missytake** [comment]
I'd like to close this issue for now, we can re-open it if the original poster re-appears and gives more information. Personally, I'm sceptical to make IPv6 opt-in, and opt-out is already supported - so to keep this open we need more arguments. And if it was actually a problem with `disable_ipv6 = True`, we need more information what went wrong.

**Comment by ccclxxiii** [comment]
@missytake here is the core issue i see.  

when unbound deploys by default it will listen on `ipv4` and `ipv6`.  the machine it was deployed to couldn't bind unbound to the interface since the expectation was to have `ipv6` enabled.  this caused the `cmdeploy run` to fail with a systemd journal entry noting it could not bind the interface.

as a patch i created `/etc/unbound/unbound.conf.d/custom-interfaces.conf`

as:

````
server:
    interface: 127.0.0.1
    do-ip6: no
    interface-automatic: no
````

sighup'd unbound, and then re-deployed and it worked.

it seems the case for `disable_ipv6 = True` has no effect on the unbound service whether `True || False`

as for postfix, i've deployed a new relay and it failed without changing `mynetworks` in `/etc/postfix/main.cf`

`mynetworks = 127.0.0.0/8`

py infra will overwrite this each time you perform a `cmdeploy run` so it may be something we consider with `.j2` templating for `postfix` and `unbound`  

likely a pr i can make if there's interest in fixing it.

cc: @feld

**Comment by adbenitez** [comment]
that was also my experience when deploying chatmail in a server that had IPv6 disabled by default (Contabo), even if I was providing the `disable_ipv6=True` in `chatmail.ini` this was still failing

**Comment by ccclxxiii** [comment]
fixed in #832
